### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by generaldamras** [meffmadd/pandas-visual-analysis#5]
My issue is in both JupyterLab and Jupyter Notebooks.

In JupyterLab, if I use VisualAnalysis, I get the error:

`Error displaying widget: model not found`

This happens whether or not I use the magic commands `%matplotlib widget` or `%matplotlib inline`.

If I use Jupyter Notebook instead, I get no output at all: no figure and no error message.

This is example code that exhibits this behavior: 

```
import numpy as np
import pandas as pd
from pandas_visual_analysis import VisualAnalysis

VisualAnalysis(pd.DataFrame(np.random.rand(4,5)))
```

I'm on python==3.6.12, jupyterlab==2.2.6, and pandas-visual-analysis==0.0.4

One of my points of confusion is how it's *supposed* to work. In the docs, we see that no magic commands are used at all. Just importing the package and calling it the first time should work. From my experience, which is limited, I have to always use a magic command on matplotlib to plot *anything* in a notebook, and I must use the `widget` option to get interactive plots.

**Comment by meffmadd** [comment]
Hi!

PVA uses plotly for displaying figures, so it has nothing to do with matplotlib. Getting it to work requires plotly to work in jupyterlab, which requires some lab-extensions. Following this guide by plotly should hopefully resolve your issue: https://plotly.com/python/getting-started/#jupyterlab-support-python-35

Generally when working with notebooks you also need the `jupyter-client` and `jupyter-core` packages. If you haven't already, you can install these packages with `pip install pandas-visual-analysis[notebook]`.

Thanks for using Pandas Visual Analysis and pointing out this issue! I will update the documentation. Please let me know if that resolved your issue.

**Comment by generaldamras** [comment]
Thanks for the plotly link. Following the instructions exactly made it work. My issues all seem to be resolved now. Thanks for the prompt reply!

I think my issues stemmed from a combination of not knowing how to manage my pip/conda environment, and confusion about how plotly worked. I'm using a conda virtual environment, but some of my packages were installed with pip. I had pip installed plotly, but, following the guide, using `conda install` and the additional `jupyter labextension` commands fixed my issues. 

I will admit that I've never used `plotly` before, so that's why I didn't know how/if `matplotlib` was involved. This package is exactly what I've been looking for for quite some time now, so I'm glad to have it running.
